services:
  database:
    image: postgres:17.4-alpine3.21
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
